% Script generated by Brainstorm (08-Mar-2018)
ProtocolInfo = bst_get('ProtocolInfo');
Path_bs = [ProtocolInfo.STUDIES filesep];
PATHOUT ='E:\Inhibition\inhibition_data\source_data\repeat\high_high\';
PATHOUT_spgranger='E:\Inhibition\inhibition_data\FC_data\repeat\high_high\spgranger\';
cd(PATHOUT);
list=dir('sub*');  % reads all .set files in that path
len=length(list); 
for s=1:len
    cd([PATHOUT,filesep,'sub',num2str(s),filesep,'ERP_data'])
    list1=dir('data_ERP_data*');
    length(list1)
    sFiles=cell(1,length(list1)-1);
    % Input files
    for i=1:length(list1)-1
        sFiles(i)={['sub',num2str(s),'/','ERP_data','/',list1(i).name]};
    end
    % Start a new report
    bst_report('Start', sFiles);
    % Process: Bivariate Granger causality (spectral) NxN
    sFiles = bst_process('CallProcess', 'process_spgranger1n', sFiles, [], ...
        'timewindow',   [-0.35, 0.998], ...
        'dest_sensors', 'MEG, EEG', ...
        'includebad',   1, ...
        'removeevoked', 0, ...
        'grangerorder', 10, ...
        'maxfreqres',   2, ...
        'maxfreq',      100, ...
        'outputmode',   1);  % Save individual results (one file per input file)
end
%% %%%%%%%%%%%%%%%%% save correction_data
cd(Path_bs)
% select all subject folders
list=dir('sub*');
len=length(list);
subj=[];
subj = {list.name};
sFiles = [];
ProtocolInfo = bst_get('ProtocolInfo');
Path_bs = [ProtocolInfo.STUDIES filesep];
for s=1:len
    %%%
    sFiles=cell(1,length(list1)-1);
    for i=1:length(list1)-1
        sFiles(i)={['sub',num2str(s),'/','ERP_data','/',list1(i).name]};
    end
    clear FC_data;
    files=dir([Path_bs, subj{s}, filesep,'ERP_data', filesep, 'timefreq_connectn_spgranger*']);
    load([Path_bs,subj{s}, filesep,'ERP_data', filesep,files(1).name]);
    for i=1:length(files)
        load([Path_bs,subj{s}, filesep,'ERP_data', filesep,files(i).name])
        FC_data{i}.pte=TF;
        FC_data{i}.channel=RowNames;
        FC_data{i}.Freqs=Freqs;
    end
    save([PATHOUT_spgranger,num2str(s),'_spgranger.mat'],'FC_data');
end