ProtocolInfo = bst_get('ProtocolInfo');
Path_bs = [ProtocolInfo.STUDIES filesep];
PATHOUT ='E:\target\source_data\target3\switch\';
PATHOUT_pac='E:\target\PAC_data\target3\switch\';
%%
% Script generated by Brainstorm (08-Mar-2018)
cd(PATHOUT);
list=dir('sub*');  % reads all .set files in that path
len=length(list); 
for s=1:len
    cd([PATHOUT,filesep,'sub',num2str(s),filesep,'ERP_data'])
    list1=dir('data_ERP_data*');
    length(list1)
    sFiles=cell(1,length(list1)-1);
    % Input files
    for i=1:length(list1)-1
        sFiles(i)={['sub',num2str(s),'/','ERP_data','/',list1(i).name]};
    end
    % Start a new report
    bst_report('Start', sFiles);
    % Process: Phase-amplitude coupling
    sFiles = bst_process('CallProcess', 'process_pac', sFiles, [], ...
        'timewindow',     [-0.35, 0.998], ...
        'target_data',    'MEG, EEG', ...
        'nesting',        [4, 12], ...
        'nested',         [15, 49], ...
        'numfreqs',       0, ...
        'parallel',       0, ...
        'ismex',          1, ...
        'max_block_size', 1, ...
        'avgoutput',      0, ...
        'savemax',        0,...
        'outputmode',   1,...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
end
%%
% Save and display report
cd(Path_bs)
% select all subject folders
list=dir('sub*');
len=length(list);
subj=[];
subj = {list.name};
sFiles = [];
ProtocolInfo = bst_get('ProtocolInfo');
Path_bs = [ProtocolInfo.STUDIES filesep];
for s=1:len
    %
    sFiles=cell(1,length(list1)-1);
    for i=1:length(list1)-1
        sFiles(i)={['sub',num2str(s),'/','ERP_data','/',list1(i).name]};
    end
    clear PAC_data;
    files=dir([Path_bs, subj{s}, filesep,'ERP_data', filesep, 'timefreq_pac_fullmaps*']);
    load([Path_bs,subj{s}, filesep,'ERP_data', filesep,files(1).name]);
    for i=1:length(files)
        load([Path_bs,subj{s}, filesep,'ERP_data', filesep,files(i).name])
        PAC_data{i}.pac=sPAC;
    end
    save([PATHOUT_pac,num2str(s),'_pac.mat'],'PAC_data');
end





