%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% [ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
% PATHIN='/home/wangyu/Desktop/Emotion/After/ERP_data/Negative/';
% for i=1:20
%     EEG = pop_loadset('filename',[num2str(i),'.set'],'filepath',PATHIN);
%     [ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
%     EEG = eeg_checkset( EEG );
%     EEG = pop_saveset( EEG, 'filename',['sub',num2str(i),'.set'],'filepath',PATHIN);
%     [ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
%     STUDY = []; CURRENTSTUDY = 0; ALLEEG = []; EEG=[]; CURRENTSET=[];
% end
% PATHIN='/home/wangyu/Desktop/Emotion/After/ERP_data/Neutral/';
% for i=1:20
%     EEG = pop_loadset('filename',[num2str(i),'.set'],'filepath',PATHIN);
%     [ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
%     EEG = eeg_checkset( EEG );
%     EEG = pop_saveset( EEG, 'filename',['sub',num2str(i),'.set'],'filepath',PATHIN);
%     [ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
%     STUDY = []; CURRENTSTUDY = 0; ALLEEG = []; EEG=[]; CURRENTSET=[];
% end
% PATHIN='/home/wangyu/Desktop/Emotion/After/ERP_data/Positive/';
% for i=1:20
%     EEG = pop_loadset('filename',[num2str(i),'.set'],'filepath',PATHIN);
%     [ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
%     EEG = eeg_checkset( EEG );
%     EEG = pop_saveset( EEG, 'filename',['sub',num2str(i),'.set'],'filepath',PATHIN);
%     [ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
%     STUDY = []; CURRENTSTUDY = 0; ALLEEG = []; EEG=[]; CURRENTSET=[];
% end

%% Directories
clear;
close all;

MAINPATH ='E:\';
PATHIN  ='E:\target\target8\switch_data\';      % path containing rawdata
PATHOUT ='E:\target\source_data\target8\switch\';  % path for script output
% ** set path to your current brainstorm protocol. The function will create
% the path based on the currently open protocol of your brainstorm database
% Make sure that you have the right protocol selected.
ProtocolInfo = bst_get('ProtocolInfo');
Path_bs = [ProtocolInfo.STUDIES filesep];

% ** set the folder with your electrode position file
elec_file = fullfile(MAINPATH,'config','elec_file.xyz');

% specific brainstorm variable used for all processes
sFiles = [];


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 1. Import and process data with brainstorm %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% locate pre-processed datasets
cd(PATHIN)
list=dir('*set'); % reads all .set files in that path
len=length(list);   % total number of datasets that will be evaluated

for s = 1:len
    subj{s} = strrep(list(s).name, list(s).name(end-3:end), '');
    % start a new report
    bst_report('Start', sFiles);
    
    % process: Import MEG/EEG: Existing epochs
    sFiles = bst_process('CallProcess', 'process_import_data_epoch', ...
        sFiles, [], ...
        'subjectname',  subj{s}, ...
        'condition',    '', ...
        'datafile',     {{[PATHIN list(s).name ]}, 'EEG-EEGLAB'}, ...
        'iepochs',      [], ...
        'eventtypes',   'type', ...
        'createcond',   1, ...
        'channelalign', 0, ...
        'usectfcomp',   0, ...
        'usessp',       0, ...
        'freq',         [], ...
        'baseline',     []);
    
    
    % process: Set channel file
    sFiles = bst_process(...
        'CallProcess', 'process_import_channel', ...
        sFiles, [], ...
        'channelfile', {elec_file, 'EEGLAB'}, ...
        'usedefault', 1, ...
        'channelalign', 0);
    
    % process: Compute covariance (noise or data)
    sFiles = bst_process('CallProcess', 'process_noisecov', sFiles, [], ...
        'baseline',       [-0.35, 0], ...
        'datatimewindow', [], ...
        'sensortypes',    '', ...
        'target',         1, ...
        'dcoffset',       1, ...
        'identity',       0, ...
        'copycond',       0, ...
        'copysubj',       0, ...
        'replacefile',    1);
    
    
    % process: Average: Everything (*what is averaged depends on your
    % experimental conditions)
    sFiles = bst_process('CallProcess', 'process_average', sFiles, [], ...
        'avgtype',    1, ...  % Everything
        'avg_func',   1, ...  % Arithmetic average:  mean(x)
        'weighted',   0, ...
        'keepevents', 0);
    
    % process: Compute head model (as we use default anatomy, we only need
    % to compute the head model for the 1st subject and we can copy the
    % information to all other subjects, mainly to save some computation
    % time
    if s == 1
        sFiles = bst_process('CallProcess', 'process_headmodel', sFiles, [], ...
            'Comment',     '', ...
            'sourcespace', 1, ...  % Cortex surface
            'volumegrid',  [], ...
            'meg',         2, ...  % Single sphere
            'eeg',         3, ...  % OpenMEEG BEM
            'ecog',        2, ...  % OpenMEEG BEM
            'seeg',        2, ...  % OpenMEEG BEM
            'openmeeg',    struct(...
            'BemFiles',     {{}}, ...
            'BemNames',     {{'Scalp', 'Skull', 'Brain'}}, ...
            'BemCond',      [1, 0.0125, 1], ...
            'BemSelect',    [1, 1, 1], ...
            'isAdjoint',    0, ...
            'isAdaptative', 1, ...
            'isSplit',      0, ...
            'SplitLength',  4000));
        % Get new head model file
        sHeadModel = bst_get('HeadModelForStudy', sFiles(1).iStudy);
    else
        %copy head model computed for the first participant to the current
        %subject
        [sDefaultStudy, iDefaultStudy] = bst_get('DefaultStudy', sFiles(1).SubjectFile)
        db_add(iDefaultStudy , sHeadModel.FileName);
    end
    
    
    % process: Compute sources (2016)
    sFiles = bst_process('CallProcess', 'process_inverse_2016', sFiles, [], ...
        'output',  2, ...  % Kernel only: one per file
        'inverse', struct(...
        'Comment',        'dSPM: EEG', ...
        'InverseMethod',  'minnorm', ...
        'InverseMeasure', 'dspm', ...
        'SourceOrient',   {{'fixed'}}, ...
        'Loose',          0.2, ...
        'UseDepth',       1, ...
        'WeightExp',      0.5, ...
        'WeightLimit',    10, ...
        'NoiseMethod',    'reg', ...
        'NoiseReg',       0.1, ...
        'SnrMethod',      'fixed', ...
        'SnrRms',         1e-06, ...
        'SnrFixed',       3, ...
        'ComputeKernel',  1, ...
        'DataTypes',      {{'EEG'}}));
    
    % save and display report
%     ReportFile = bst_report('Save', sFiles);
%     bst_report('Open', ReportFile);
    
    % clear brainstorm variable sFiles
    sFiles=[];
    
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%  2. Extract time series of modeled source activity for pre-defined scout
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% change directory to current brainstorm database
cd(Path_bs)
% select all subject folders
list=dir('sub*');
len=length(list);
subj = {list.name};

for s=1:len
    % locate all source file of the current subject in the bs database
    subj{s} = list(s).name;
    results_files=dir([Path_bs subj{s} filesep 'ERP_data' filesep 'results*']);
    % combine path and file name
    source_file = [subj{s} filesep 'ERP_data' filesep results_files.name];
    
    % Start a new report
    bst_report('Start', sFiles);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_Ins_lg_and_S_cent_ins R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_Ins_lg_and_S_cent_ins L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_cingul-Ant R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_cingul-Ant L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_cingul-Mid-Ant R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_cingul-Mid-Ant L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_cingul-Mid-Post R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_cingul-Mid-Post L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_frontomargin R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_frontomargin L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_occipital_inf R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_occipital_inf L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_paracentral R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_paracentral L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_subcentral R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_subcentral L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_transv_frontopol R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_and_S_transv_frontopol L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_cingul-Post-dorsal R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_cingul-Post-dorsal L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_cingul-Post-ventral R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_cingul-Post-ventral L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_cuneus R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_cuneus L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_front_inf-Opercular R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_front_inf-Opercular L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_front_inf-Orbital R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_front_inf-Orbital L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_front_inf-Triangul R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_front_inf-Triangul L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_front_middle R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_front_middle L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_front_sup R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_front_sup L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_insular_short R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_insular_short L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_oc-temp_lat-fusifor R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_oc-temp_lat-fusifor L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_oc-temp_med-Lingual R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_oc-temp_med-Lingual L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_oc-temp_med-Parahip R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_oc-temp_med-Parahip L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_occipital_middle R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_occipital_middle L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_occipital_sup R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_occipital_sup L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_orbital R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_orbital L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_pariet_inf-Angular R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_pariet_inf-Angular L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_pariet_inf-Supramar R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_pariet_inf-Supramar L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_parietal_sup R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_parietal_sup L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_postcentral R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_postcentral L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_precentral R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_precentral L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_precuneus R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_precuneus L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_rectus R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_rectus L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_subcallosal R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_subcallosal L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_temp_sup-G_T_transv R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_temp_sup-G_T_transv L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_temp_sup-Lateral R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_temp_sup-Lateral L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_temp_sup-Plan_polar R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_temp_sup-Plan_polar L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_temp_sup-Plan_tempo R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_temp_sup-Plan_tempo L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_temporal_inf R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_temporal_inf L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_temporal_middle R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'G_temporal_middle L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'Lat_Fis-ant-Horizont R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'Lat_Fis-ant-Horizont L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'Lat_Fis-ant-Vertical R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'Lat_Fis-ant-Vertical L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'Lat_Fis-post R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'Lat_Fis-post L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'Pole_occipital R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'Pole_occipital L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'Pole_temporal R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'Pole_temporal L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_calcarine R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_calcarine L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_central R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_central L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_cingul-Marginalis R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_cingul-Marginalis L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_circular_insula_ant R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_circular_insula_ant L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_circular_insula_inf R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_circular_insula_inf L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_circular_insula_sup R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_circular_insula_sup L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_collat_transv_ant R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_collat_transv_ant L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_collat_transv_post R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_collat_transv_post L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_front_inf R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_front_inf L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_front_middle R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_front_middle L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_front_sup R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_front_sup L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_interm_prim-Jensen R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_interm_prim-Jensen L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_intrapariet_and_P_trans R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_intrapariet_and_P_trans L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_oc-temp_lat R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_oc-temp_lat L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_oc-temp_med_and_Lingual R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_oc-temp_med_and_Lingual L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_oc_middle_and_Lunatus R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_oc_middle_and_Lunatus L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_oc_sup_and_transversal R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_oc_sup_and_transversal L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_occipital_ant R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_occipital_ant L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_orbital-H_Shaped R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_orbital-H_Shaped L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_orbital_lateral R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_orbital_lateral L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_orbital_med-olfact R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_orbital_med-olfact L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_parieto_occipital R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_parieto_occipital L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_pericallosal R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_pericallosal L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_postcentral R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_postcentral L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_precentral-inf-part R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_precentral-inf-part L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_precentral-sup-part R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_precentral-sup-part L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_suborbital R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_suborbital L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_subparietal R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_subparietal L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_temporal_inf R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_temporal_inf L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_temporal_sup R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_temporal_sup L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    %%
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_temporal_transverse R'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    sFiles = bst_process('CallProcess', 'process_extract_scout', ...
        source_file, [], ...
        'timewindow',     [], ...
        'scouts',         {'Destrieux', {'S_temporal_transverse L'}}, ...
        'scoutfunc',      1, ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);
    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
    
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 3. export time series of scouts to matlab workspace and save to MAT-file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% change directory to current brainstorm database
cd(Path_bs)
% select all subject folders
list=dir('sub*');
len=length(list);
subj=[];
subj = {list.name};
sFiles = [];
% name of scouts of which time series should be saved
% here: AC_R: right auditory cortex; AC_L: left audiory cortex
scout = {'G_Ins_lg_and_S_cent_ins_L','G_Ins_lg_and_S_cent_ins_R','G_and_S_cingul_Ant_L','G_and_S_cingul_Ant_R','G_and_S_cingul_Mid_Ant_L','G_and_S_cingul_Mid_Ant_R',...
    'G_and_S_cingul_Mid_Post_L','G_and_S_cingul_Mid_Post_R','G_and_S_frontomargin_L','G_and_S_frontomargin_R','G_and_S_occipital_inf_L','G_and_S_occipital_inf_R',...
    'G_and_S_paracentral_L','G_and_S_paracentral_R','G_and_S_subcentral_L','G_and_S_subcentral_R','G_and_S_transv_frontopol_L','G_and_S_transv_frontopol_R',...
    'G_cingul_Post_dorsal_L','G_cingul_Post_dorsal_R','G_cingul_Post_ventral_L','G_cingul_Post_ventral_R','G_cuneus_L','G_cuneus_R','G_front_inf_Opercular_L',...
    'G_front_inf_Opercular_R','G_front_inf_Orbital_L','G_front_inf_Orbital_R','G_front_inf_Triangul_L','G_front_inf_Triangul_R','G_front_middle_L','G_front_middle_R',...
    'G_front_sup_L','G_front_sup_R','G_insular_short_L','G_insular_short_R','G_oc_temp_lat_fusifor_L','G_oc_temp_lat_fusifor_R','G_oc_temp_med_Lingual_L',...
    'G_oc_temp_med_Lingual_R','G_oc_temp_med_Parahip_L','G_oc_temp_med_Parahip_R','G_occipital_middle_L','G_occipital_middle_R','G_occipital_sup_L','G_occipital_sup_R',...
    'G_orbital_L','G_orbital_R','G_pariet_inf_Angular_L','G_pariet_inf_Angular_R','G_pariet_inf_Supramar_L','G_pariet_inf_Supramar_R','G_parietal_sup_L','G_parietal_sup_R',...
    'G_postcentral_L','G_postcentral_R','G_precentral_L','G_precentral_R','G_precuneus_L','G_precuneus_R','G_rectus_L','G_rectus_R','G_subcallosal_L','G_subcallosal_R',...
    'G_temp_sup_G_T_transv_L','G_temp_sup_G_T_transv_R','G_temp_sup_Lateral_L','G_temp_sup_Lateral_R','G_temp_sup_Plan_polar_L','G_temp_sup_Plan_polar_R','G_temp_sup_Plan_tempo_L',...
    'G_temp_sup_Plan_tempo_R','G_temporal_inf_L','G_temporal_inf_R','G_temporal_middle_L','G_temporal_middle_R','Lat_Fis_ant_Horizont_L','Lat_Fis_ant_Horizont_R',...
    'Lat_Fis_ant_Vertical_L','Lat_Fis_ant_Vertical_R','Lat_Fis_post_L','Lat_Fis_post_R','Pole_occipital_L','Pole_occipital_R','Pole_temporal_L','Pole_temporal_R',...
    'S_calcarine_L','S_calcarine_R','S_central_L','S_central_R','S_cingul_Marginalis_L','S_cingul_Marginalis_R','S_circular_insula_ant_L','S_circular_insula_ant_R',...
    'S_circular_insula_inf_L','S_circular_insula_inf_R','S_circular_insula_sup_L','S_circular_insula_sup_R','S_collat_transv_ant_L','S_collat_transv_ant_R','S_collat_transv_post_L',...
    'S_collat_transv_post_R','S_front_inf_L','S_front_inf_R','S_front_middle_L','S_front_middle_R','S_front_sup_L','S_front_sup_R','S_interm_prim_Jensen_L','S_interm_prim_Jensen_R',...
    'S_intrapariet_and_P_trans_L','S_intrapariet_and_P_trans_R','S_oc_temp_lat_L','S_oc_temp_lat_R','S_oc_temp_med_and_Lingual_L','S_oc_temp_med_and_Lingual_R',...
    'S_oc_middle_and_Lunatus_L','S_oc_middle_and_Lunatus_R','S_oc_sup_and_transversal_L','S_oc_sup_and_transversal_R','S_occipital_ant_L','S_occipital_ant_R',...
    'S_orbital_H_Shaped_L','S_orbital_H_Shaped_R','S_orbital_lateral_L','S_orbital_lateral_R','S_orbital_med_olfact_L','S_orbital_med_olfact_R','S_parieto_occipital_L',...
    'S_parieto_occipital_R','S_pericallosal_L','S_pericallosal_R','S_postcentral_L','S_postcentral_R','S_precentral_inf_part_L','S_precentral_inf_part_R','S_precentral_sup_part_L',...
    'S_precentral_sup_part_R','S_suborbital_L','S_suborbital_R','S_subparietal_L','S_subparietal_R','S_temporal_inf_L','S_temporal_inf_R','S_temporal_sup_L','S_temporal_sup_R',...
    'S_temporal_transverse_L','S_temporal_transverse_R'};
for s=1:len
    % locate path of source results file
    files=dir([Path_bs, subj{s}, filesep,'ERP_data', filesep, 'matrix_scout_*']);
    sFiles=strcat({Path_bs}, subj{s}, filesep,'ERP_data', filesep, {files(:).name});
    % export to matlab workspace and save
    for i= 1:length(sFiles)
        export_matlab(sFiles(i), [scout{i}])   %subj{s}, '_', 
        save([PATHOUT,'sub',num2str(s),filesep,scout{i}, '.mat'], [scout{i}])
    end
end
% cd(fullfile(MAINPATH, 'scripts', filesep));