% Script generated by Brainstorm (08-Mar-2018)
ProtocolInfo = bst_get('ProtocolInfo');
Path_bs = [ProtocolInfo.STUDIES filesep];
PATHOUT ='E:\Inhibition\inhibition_data\source_data\repeat\high_high\';
PATHOUT_granger='E:\Inhibition\inhibition_data\FC_data\repeat\high_high\granger\';
cd(PATHOUT);
list=dir('sub*');  % reads all .set files in that path
len=length(list); 
for s=1:len
    cd([PATHOUT,filesep,'sub',num2str(s),filesep,'ERP_data'])
    list1=dir('data_ERP_data*');
    length(list1)
    sFiles=cell(1,length(list1)-1);
    % Input files
    for i=1:length(list1)-1
        sFiles(i)={['sub',num2str(s),'/','ERP_data','/',list1(i).name]};
    end
    % Start a new report
    bst_report('Start', sFiles);
    % Process: Bivariate Granger causality NxN
    sFiles = bst_process('CallProcess', 'process_granger1n', sFiles, [], ...
        'timewindow',   [-0.35, 0.998], ...
        'dest_sensors', 'MEG, EEG', ...
        'includebad',   1, ...
        'removeevoked', 0, ...
        'grangerorder', 10, ...
        'outputmode',   1,...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', 1);  % Save individual results (one file per input file)
end
%% %%%%%%%%%%%%%%%%% save correction_data
cd(Path_bs)
% select all subject folders
list=dir('sub*');
len=length(list);
subj=[];
subj = {list.name};
sFiles = [];
ProtocolInfo = bst_get('ProtocolInfo');
Path_bs = [ProtocolInfo.STUDIES filesep];
for s=1:len
    %%%
    sFiles=cell(1,length(list1)-1);
    for i=1:length(list1)-1
        sFiles(i)={['sub',num2str(s),'/','ERP_data','/',list1(i).name]};
    end
    clear FC_data;
    files=dir([Path_bs, subj{s}, filesep,'ERP_data', filesep, 'timefreq_connectn_granger*']);
    load([Path_bs,subj{s}, filesep,'ERP_data', filesep,files(1).name]);
    for i=1:length(files)
        load([Path_bs,subj{s}, filesep,'ERP_data', filesep,files(i).name])
        FC_data{i}.granger=TF;
        FC_data{i}.channel=RowNames;
    end
    save([PATHOUT_granger,num2str(s),'_granger.mat'],'FC_data');
end